### ISSUE TITLE
shell container addition returns a syntax error warning

### ISSUE THREAD

**Issue by andrewdobson** [ros-visualization/rqt_console#5]
when I add a shell container to an empty rqt environment, I get the following error:

```
`PluginManager._load_plugin() could not load plugin "rqt_shell/Shell":
Traceback (most recent call last):
  File "/opt/clearpath/2.6pre/sdk/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 99, in load
    self._load()
  File "/opt/clearpath/2.6pre/sdk/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 54, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/clearpath/2.6pre/sdk/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/clearpath/2.6pre/sdk/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 83, in load
    raise e
  File "/opt/clearpath/2.6pre/sdk/lib/python2.7/dist-packages/rqt_shell/spyder_shell_widget.py", line 109
    "-c 'source %s; /bin/bash -i'" % os.path.abspath(script_path)])
                                                                  ^
SyntaxError: invalid syntax`
```

system info
ubuntu 14.04
ros indigo
Utilized libraries:: Python 2.7.6, rospkg 1.1.2, PyQt 4.10.4 (QtCore, QtDeclarative, QtGui, QtNetwork, QtOpenGL, QtScript, QtSvg, QtWebKit, QtWidgets, QtXml, QtXmlPatterns, Qwt), Qt 4.8.6, SIP C++ bindings available.

repeatable on multiple physical computers running the same OS

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_shell#5
